dev:
  resource_group: hupiukko-dev-rg
  location: swedencentral
  app_service_name: hupiukko-frontend-appservice-dev
  app_service_plan: hupiukko-appserviceplan-dev
  key_vault: hupiukko-keyvault-dev
  param_file: infra/parameters/dev.bicepparam
  sql_server_name: hupiukko-sql-dev
  sql_db_name: hupiukko-db-dev
  migration_sp_name: github-actions-hupiukko
  backend_mi_name: hupiukko-backend-identity
prod:
  resource_group: hupiukko-prod-rg
  location: swedencentral
  app_service_name: hupiukko-frontend-appservice-prod
  app_service_plan: hupiukko-appserviceplan-prod
  key_vault: hupiukko-keyvault-prod
  param_file: infra/parameters/prod.bicepparam
  sql_server_name: hupiukko-sql-prod
  sql_db_name: hupiukko-db-prod
  migration_sp_name: github-actions-hupiukko
  backend_mi_name: hupiukko-backend-identity 