name: Deploy Azure Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.43.1/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Export all environment variables for selected environment
        run: |
          for row in $(yq ".${{ matrix.environment }} | to_entries | .[] | @base64" environments.yml); do
            _jq() {
              echo ${row} | base64 --decode | jq -r '.key + "=" + .value'
            }
            echo $(_jq) >> $GITHUB_ENV
          done
        env:
          ENVIRONMENT: ${{ matrix.environment }}

      - name: Deploy Infrastructure
        run: |
          az deployment group create \
            --resource-group ${{ env.resource_group }} \
            --template-file infra/main.bicep \
            --parameters @${{ env.param_file }} 