name: Deploy Azure Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod
      preview:
        description: 'Preview only (what-if)?'
        required: false
        default: false
        type: boolean
      services:
        description: 'Services to deploy'
        required: true
        default: all
        type: choice
        options:
          - all
          - keyvault
          - appservice
          - none

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Export all environment variables for selected environment
        run: |
          yq ".${{ github.event.inputs.environment }} | to_entries[] | \"\(.key)=\(.value)\"" environments.yml >> $GITHUB_ENV
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}

      - name: Set deploy booleans based on service selection
        run: |
          if [[ "${{ github.event.inputs.services }}" == "all" ]]; then
            echo "DEPLOY_KEYVAULT=true" >> $GITHUB_ENV
            echo "DEPLOY_APPSERVICE=true" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.services }}" == "keyvault" ]]; then
            echo "DEPLOY_KEYVAULT=true" >> $GITHUB_ENV
            echo "DEPLOY_APPSERVICE=false" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.services }}" == "appservice" ]]; then
            echo "DEPLOY_KEYVAULT=false" >> $GITHUB_ENV
            echo "DEPLOY_APPSERVICE=true" >> $GITHUB_ENV
          else
            echo "DEPLOY_KEYVAULT=false" >> $GITHUB_ENV
            echo "DEPLOY_APPSERVICE=false" >> $GITHUB_ENV
          fi

      - name: Print deployment parameters
        run: cat infra/parameters/${{ github.event.inputs.environment }}.parameters.json

      - name: Preview Bicep deployment (what-if)
        if: ${{ github.event.inputs.preview == 'true' }}
        run: |
          az deployment group what-if \
            --resource-group ${{ env.resource_group }} \
            --template-file infra/main.bicep \
            --parameters @infra/parameters/${{ github.event.inputs.environment }}.parameters.json \
            deployKeyVault=${{ env.DEPLOY_KEYVAULT }} \
            deployAppService=${{ env.DEPLOY_APPSERVICE }}

      - name: Deploy Bicep file
        if: ${{ github.event.inputs.preview != 'true' }}
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.resource_group }}
          template: infra/main.bicep
          parameters: >
            @infra/parameters/${{ github.event.inputs.environment }}.parameters.json
            deployKeyVault=${{ env.DEPLOY_KEYVAULT }}
            deployAppService=${{ env.DEPLOY_APPSERVICE }}
          failOnStdErr: false