name: Build and Deploy Backend

on:
  push:
    branches: [main]
    paths: ['backend/**']
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export environment variables
        run: |
          yq ".${{ github.event.inputs.environment || 'dev' }} | to_entries[] | \"\(.key)=\(.value)\"" environments.yml >> $GITHUB_ENV
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment || 'dev' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container
        uses: docker/build-push-action@v5
        with:
          context: ./backend/Hupiukko.Api
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.container_image_name }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ env.container_image_name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.backend_app_service_name }}
          images: ghcr.io/${{ github.repository_owner }}/${{ env.container_image_name }}:${{ github.sha }}

      - name: Verify deployment
        run: |
          echo "✅ Backend deployed successfully to ${{ env.backend_app_service_name }}"
          echo "Image: ghcr.io/${{ github.repository_owner }}/${{ env.container_image_name }}:${{ github.sha }}"
          echo "Environment: ${{ github.event.inputs.environment || 'dev' }}"
