name: Deploy Azure Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Export all environment variables for selected environment
        run: |
          yq ".${{ github.event.inputs.environment }} | to_entries[] | \"\(.key)=\(.value)\"" environments.yml >> $GITHUB_ENV
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}

      - name: Prepare parameters file for deployment
        run: |
          grep -v '^using ' infra/parameters/${{ github.event.inputs.environment }}.bicepparam > params.cicd.bicepparam

      - name: Deploy Infrastructure
        run: |
          az deployment group create \
            --resource-group ${{ env.resource_group }} \
            --template-file infra/main.bicep \
            --parameters @params.cicd.bicepparam 